/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppuntamentiRouteImport } from './routes/appuntamenti'
import { Route as ApriRouteImport } from './routes/apri'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrenotaRouteImport } from './routes/prenota'
import { Route as QrRouteImport } from './routes/qr'
import { Route as SalaRouteImport } from './routes/sala'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppuntamentiRoute = AppuntamentiRouteImport.update({
  id: '/appuntamenti',
  path: '/appuntamenti',
  getParentRoute: () => rootRouteImport,
} as any)
const ApriRoute = ApriRouteImport.update({
  id: '/apri',
  path: '/apri',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrenotaRoute = PrenotaRouteImport.update({
  id: '/prenota',
  path: '/prenota',
  getParentRoute: () => rootRouteImport,
} as any)
const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaRoute = SalaRouteImport.update({
  id: '/sala',
  path: '/sala',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appuntamenti': typeof AppuntamentiRoute
  '/apri': typeof ApriRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/qr': typeof QrRoute
  '/sala': typeof SalaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appuntamenti': typeof AppuntamentiRoute
  '/apri': typeof ApriRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/qr': typeof QrRoute
  '/sala': typeof SalaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appuntamenti': typeof AppuntamentiRoute
  '/apri': typeof ApriRoute
  '/chat': typeof ChatRoute
  '/login': typeof LoginRoute
  '/prenota': typeof PrenotaRoute
  '/qr': typeof QrRoute
  '/sala': typeof SalaRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appuntamenti'
    | '/apri'
    | '/chat'
    | '/login'
    | '/prenota'
    | '/qr'
    | '/sala'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appuntamenti'
    | '/apri'
    | '/chat'
    | '/login'
    | '/prenota'
    | '/qr'
    | '/sala'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/appuntamenti'
    | '/apri'
    | '/chat'
    | '/login'
    | '/prenota'
    | '/qr'
    | '/sala'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppuntamentiRoute: typeof AppuntamentiRoute
  ApriRoute: typeof ApriRoute
  ChatRoute: typeof ChatRoute
  LoginRoute: typeof LoginRoute
  PrenotaRoute: typeof PrenotaRoute
  QrRoute: typeof QrRoute
  SalaRoute: typeof SalaRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appuntamenti': {
      id: '/appuntamenti'
      path: '/appuntamenti'
      fullPath: '/appuntamenti'
      preLoaderRoute: typeof AppuntamentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apri': {
      id: '/apri'
      path: '/apri'
      fullPath: '/apri'
      preLoaderRoute: typeof ApriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prenota': {
      id: '/prenota'
      path: '/prenota'
      fullPath: '/prenota'
      preLoaderRoute: typeof PrenotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala': {
      id: '/sala'
      path: '/sala'
      fullPath: '/sala'
      preLoaderRoute: typeof SalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppuntamentiRoute: AppuntamentiRoute,
  ApriRoute: ApriRoute,
  ChatRoute: ChatRoute,
  LoginRoute: LoginRoute,
  PrenotaRoute: PrenotaRoute,
  QrRoute: QrRoute,
  SalaRoute: SalaRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
